version: '3.5'
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "jack-bot:latest"
    entrypoint:
      - "python"
      - "main.py"
      - "-c"
      - "configs/api.yml"
    restart: on-failure
    volumes:
      - ../logs/:/workspace/logs/
      - ../configs/:/workspace/configs/
    ports:
      - "6660:6660"
    network_mode: host

  dashboard:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "jack-bot:latest"
    entrypoint:
      - "python"
      - "main.py"
      - "-c"
      - "configs/dashboard.yml"
    restart: on-failure
    volumes:
      - ../logs/:/workspace/logs/
      - ../configs/:/workspace/configs/
    ports:
      - "8501:8501"
    links:
      - api
    depends_on:
      - api
    network_mode: host

  jack-settings:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "jack-bot:latest"
    entrypoint:
      - "python"
      - "main.py"
      - "-c"
      - "configs/jack-settings.yml"
    restart: on-failure
    volumes:
      - ../logs/:/workspace/logs/
      - ../configs/:/workspace/configs/
    ports:
      - "8502:8502"
    links:
      - api
    depends_on:
      - api
    network_mode: host
